import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import process from 'node:process';

const root = resolve(import.meta.dirname, '..');
const outputRoot = resolve(root, 'src/stories/generated');
const manifest = JSON.parse(await readFile(resolve(root, 'design-system.manifest.json'), 'utf8'));
const checkOnly = process.argv.includes('--check');
const levelTitles = {
  foundation: '01 Foundations',
  atom: '02 Atoms',
  molecule: '03 Molecules',
  organism: '04 Organisms',
  template: '05 Templates',
  page: '06 Pages',
};

function storyFor(component) {
  const variants = component.variants.length ? component.variants : ['default'];
  const states = component.states.length ? component.states : ['default'];
  // Stable machine IDs matter more than sidebar prose; the rendered docs keep the human name.
  const title = `${levelTitles[component.atomicLevel]}/${component.id}`;
  return `/* Generated by scripts/generate-stories.mjs. Do not edit directly. */\nimport type { Meta, StoryObj } from '@storybook/react-vite';\nimport { ComponentDocumentation } from '../../showcase/componentDocs';\n\nconst meta = {\n  title: ${JSON.stringify(title)},\n  component: ComponentDocumentation,\n  tags: ['autodocs'],\n  args: { componentId: ${JSON.stringify(component.id)}, variant: ${JSON.stringify(variants[0])}, state: ${JSON.stringify(states[0])}, theme: 'light', motion: 'subtle', disabled: false },\n  argTypes: {\n    componentId: { control: false, table: { disable: true } },\n    variant: { control: 'select', options: ${JSON.stringify(variants)} },\n    state: { control: 'select', options: ${JSON.stringify(states)} },\n    theme: { control: 'inline-radio', options: ['light', 'dark'] },\n    motion: { control: 'inline-radio', options: ['none', 'subtle', 'expressive'] },\n    disabled: { control: 'boolean' },\n  },\n  parameters: { docs: { description: { component: ${JSON.stringify(component.description)} } }, componentId: ${JSON.stringify(component.id)} },\n} satisfies Meta<typeof ComponentDocumentation>;\nexport default meta;\ntype Story = StoryObj<typeof meta>;\nexport const Playground: Story = {};\nexport const Variants: Story = { args: { variant: ${JSON.stringify(variants.at(-1))} } };\nexport const States: Story = { args: { state: ${JSON.stringify(states.at(-1))} } };\nexport const DarkMode: Story = { args: { theme: 'dark' } };\nexport const ReducedMotion: Story = { args: { motion: 'none' }, parameters: { reducedMotion: true } };\n`;
}

const expected = new Map(manifest.components.map((component) => [`${component.id}.stories.tsx`, storyFor(component)]));
if (checkOnly) {
  const actualNames = new Set(await readdir(outputRoot).catch(() => []));
  for (const [name, content] of expected) {
    const current = await readFile(resolve(outputRoot, name), 'utf8').catch(() => '');
    if (current !== content)
      throw new Error(`Generated story is stale: src/stories/generated/${name}. Run npm run generate.`);
    actualNames.delete(name);
  }
  if (actualNames.size) throw new Error(`Unexpected generated stories: ${[...actualNames].join(', ')}`);
} else {
  await rm(outputRoot, { recursive: true, force: true });
  await mkdir(outputRoot, { recursive: true });
  for (const [name, content] of expected) await writeFile(resolve(outputRoot, name), content, 'utf8');
}
console.log(`${checkOnly ? 'Validated' : 'Generated'} ${expected.size} individual Storybook entries.`);
