/* Generated by scripts/generate-contracts.mjs. Do not edit directly. */
export const designTokens = {
  "color": {
    "orange": {
      "50": "#fff4ed",
      "100": "#ffe4d2",
      "200": "#ffc5a3",
      "300": "#ff9e6a",
      "400": "#ff7335",
      "500": "#ff5a00",
      "600": "#e84d00",
      "700": "#b93800",
      "800": "#932f08",
      "900": "#77290d"
    },
    "neutral": {
      "0": "#ffffff",
      "50": "#faf9f8",
      "100": "#f5f2f0",
      "200": "#e7e3e0",
      "300": "#d4cfcb",
      "400": "#a8a29e",
      "500": "#797471",
      "600": "#575350",
      "700": "#3d3a38",
      "800": "#292726",
      "900": "#1d1d1f",
      "1000": "#0d0d0e"
    },
    "green": {
      "100": "#dff6ed",
      "600": "#147d57"
    },
    "blue": {
      "100": "#e4eef9",
      "700": "#24548a"
    },
    "red": {
      "100": "#fee4e2",
      "700": "#b42318"
    },
    "yellow": {
      "100": "#fff2cc",
      "800": "#7a4d00"
    },
    "brand": "#ff5a00",
    "action-primary": "#b93800",
    "action-primary-hover": "#932f08",
    "action-primary-active": "#77290d",
    "action-primary-text": "#ffffff",
    "brand-soft": "#fff4ed",
    "action-text": "#a33200",
    "canvas": "#ffffff",
    "surface": "#f5f2f0",
    "surface-raised": "#ffffff",
    "surface-hover": "#faf9f8",
    "text": "#1d1d1f",
    "text-muted": "#575350",
    "text-subtle": "#797471",
    "text-inverse": "#ffffff",
    "border": "#e7e3e0",
    "border-strong": "#a8a29e",
    "focus": "#b93800",
    "overlay": "rgb(13 13 14 / 64%)",
    "agent-thinking": "#24548a",
    "agent-running": "#b93800",
    "agent-awaiting": "#7a4d00",
    "agent-success": "#147d57",
    "agent-failed": "#b42318",
    "agent-paused": "#575350",
    "risk-low": "#147d57",
    "risk-medium": "#7a4d00",
    "risk-high": "#b42318"
  },
  "space": {
    "0": {
      "value": 0,
      "unit": "px"
    },
    "1": {
      "value": 4,
      "unit": "px"
    },
    "2": {
      "value": 8,
      "unit": "px"
    },
    "3": {
      "value": 12,
      "unit": "px"
    },
    "4": {
      "value": 16,
      "unit": "px"
    },
    "5": {
      "value": 20,
      "unit": "px"
    },
    "6": {
      "value": 24,
      "unit": "px"
    },
    "8": {
      "value": 32,
      "unit": "px"
    },
    "10": {
      "value": 40,
      "unit": "px"
    },
    "12": {
      "value": 48,
      "unit": "px"
    },
    "16": {
      "value": 64,
      "unit": "px"
    },
    "20": {
      "value": 80,
      "unit": "px"
    },
    "24": {
      "value": 96,
      "unit": "px"
    },
    "32": {
      "value": 128,
      "unit": "px"
    }
  },
  "font": {
    "sans": "'Inter Variable', Inter, ui-sans-serif, system-ui, sans-serif",
    "display": "'Clash Display', 'Inter Variable', Inter, ui-sans-serif, system-ui, sans-serif",
    "accent": "'Castledown Cursive Dots No Guide', 'Clash Display', 'Inter Variable', Inter, cursive",
    "montserrat": "'Montserrat Variable', Montserrat, 'Inter Variable', Inter, ui-sans-serif, system-ui, sans-serif",
    "mono": "'SFMono-Regular', Consolas, 'Liberation Mono', monospace"
  },
  "font-weight": {
    "regular": 400,
    "medium": 500,
    "semibold": 650,
    "bold": 750,
    "black": 850
  },
  "text": {
    "xs": "0.75rem",
    "sm": "0.875rem",
    "md": "1rem",
    "lg": "1.125rem",
    "xl": "1.375rem",
    "2xl": "clamp(1.75rem, 3vw, 2.5rem)",
    "3xl": "clamp(2.25rem, 5vw, 4rem)",
    "display": "clamp(3rem, 7vw, 6.75rem)"
  },
  "leading": {
    "tight": 0.98,
    "heading": 1.08,
    "body": 1.58
  },
  "control": {
    "sm": {
      "value": 36,
      "unit": "px"
    },
    "md": {
      "value": 44,
      "unit": "px"
    },
    "lg": {
      "value": 52,
      "unit": "px"
    }
  },
  "layout": {
    "container": "90rem",
    "content": "48rem"
  },
  "radius": {
    "xs": {
      "value": 4,
      "unit": "px"
    },
    "sm": {
      "value": 8,
      "unit": "px"
    },
    "md": {
      "value": 12,
      "unit": "px"
    },
    "lg": {
      "value": 16,
      "unit": "px"
    },
    "xl": {
      "value": 24,
      "unit": "px"
    },
    "control": {
      "value": 10,
      "unit": "px"
    },
    "card": {
      "value": 16,
      "unit": "px"
    },
    "pill": {
      "value": 999,
      "unit": "px"
    }
  },
  "shadow": {
    "sm": "0 1px 2px rgb(29 29 31 / 6%)",
    "md": "0 12px 34px rgb(29 29 31 / 10%)",
    "lg": "0 24px 70px rgb(29 29 31 / 16%)"
  },
  "duration": {
    "fast": {
      "value": 120,
      "unit": "ms"
    },
    "base": {
      "value": 180,
      "unit": "ms"
    },
    "slow": {
      "value": 280,
      "unit": "ms"
    }
  },
  "ease": {
    "standard": "cubic-bezier(0.2, 0, 0, 1)"
  },
  "z": {
    "dropdown": 30,
    "sticky": 40,
    "modal": 50,
    "toast": 60
  },
  "accent": {
    "strategy": "#8f6cad",
    "ux": "#aa2d8a",
    "technology": "#244d7e",
    "implementation": "#4d7fb8",
    "talent": "#e75a36",
    "events": "#ec7b19"
  },
  "button": {
    "background": "#1d1d1f",
    "background-primary": "#b93800",
    "background-primary-hover": "#932f08",
    "background-primary-active": "#77290d",
    "text-primary": "#ffffff",
    "background-brand": "#b93800",
    "height": {
      "value": 44,
      "unit": "px"
    },
    "radius": {
      "value": 999,
      "unit": "px"
    }
  },
  "card": {
    "background": "#ffffff",
    "background-warm": "#f5f2f0",
    "radius": {
      "value": 16,
      "unit": "px"
    }
  },
  "input": {
    "background": "#ffffff",
    "border": "#e7e3e0",
    "height": {
      "value": 44,
      "unit": "px"
    },
    "radius": {
      "value": 10,
      "unit": "px"
    }
  },
  "dialog": {
    "background": "#ffffff",
    "radius": {
      "value": 24,
      "unit": "px"
    },
    "shadow": "0 24px 70px rgb(29 29 31 / 16%)"
  },
  "badge": {
    "radius": {
      "value": 999,
      "unit": "px"
    },
    "height": {
      "value": 28,
      "unit": "px"
    }
  },
  "agent-status": {
    "thinking": "#24548a",
    "running": "#b93800",
    "awaiting": "#7a4d00",
    "success": "#147d57",
    "failed": "#b42318"
  },
  "tool-call": {
    "background": "#ffffff",
    "border": "#e7e3e0",
    "radius": {
      "value": 16,
      "unit": "px"
    }
  },
  "approval": {
    "background": "#ffffff",
    "border": "#7a4d00",
    "radius": {
      "value": 16,
      "unit": "px"
    }
  },
  "artifact": {
    "background": "#ffffff",
    "border": "#e7e3e0",
    "radius": {
      "value": 16,
      "unit": "px"
    }
  }
} as const;

export const flatTokens = {
  "color.orange.50": "#fff4ed",
  "color.orange.100": "#ffe4d2",
  "color.orange.200": "#ffc5a3",
  "color.orange.300": "#ff9e6a",
  "color.orange.400": "#ff7335",
  "color.orange.500": "#ff5a00",
  "color.orange.600": "#e84d00",
  "color.orange.700": "#b93800",
  "color.orange.800": "#932f08",
  "color.orange.900": "#77290d",
  "color.neutral.0": "#ffffff",
  "color.neutral.50": "#faf9f8",
  "color.neutral.100": "#f5f2f0",
  "color.neutral.200": "#e7e3e0",
  "color.neutral.300": "#d4cfcb",
  "color.neutral.400": "#a8a29e",
  "color.neutral.500": "#797471",
  "color.neutral.600": "#575350",
  "color.neutral.700": "#3d3a38",
  "color.neutral.800": "#292726",
  "color.neutral.900": "#1d1d1f",
  "color.neutral.1000": "#0d0d0e",
  "color.green.100": "#dff6ed",
  "color.green.600": "#147d57",
  "color.blue.100": "#e4eef9",
  "color.blue.700": "#24548a",
  "color.red.100": "#fee4e2",
  "color.red.700": "#b42318",
  "color.yellow.100": "#fff2cc",
  "color.yellow.800": "#7a4d00",
  "space.0": {
    "value": 0,
    "unit": "px"
  },
  "space.1": {
    "value": 4,
    "unit": "px"
  },
  "space.2": {
    "value": 8,
    "unit": "px"
  },
  "space.3": {
    "value": 12,
    "unit": "px"
  },
  "space.4": {
    "value": 16,
    "unit": "px"
  },
  "space.5": {
    "value": 20,
    "unit": "px"
  },
  "space.6": {
    "value": 24,
    "unit": "px"
  },
  "space.8": {
    "value": 32,
    "unit": "px"
  },
  "space.10": {
    "value": 40,
    "unit": "px"
  },
  "space.12": {
    "value": 48,
    "unit": "px"
  },
  "space.16": {
    "value": 64,
    "unit": "px"
  },
  "space.20": {
    "value": 80,
    "unit": "px"
  },
  "space.24": {
    "value": 96,
    "unit": "px"
  },
  "space.32": {
    "value": 128,
    "unit": "px"
  },
  "font.sans": "'Inter Variable', Inter, ui-sans-serif, system-ui, sans-serif",
  "font.display": "'Clash Display', 'Inter Variable', Inter, ui-sans-serif, system-ui, sans-serif",
  "font.accent": "'Castledown Cursive Dots No Guide', 'Clash Display', 'Inter Variable', Inter, cursive",
  "font.montserrat": "'Montserrat Variable', Montserrat, 'Inter Variable', Inter, ui-sans-serif, system-ui, sans-serif",
  "font.mono": "'SFMono-Regular', Consolas, 'Liberation Mono', monospace",
  "font-weight.regular": 400,
  "font-weight.medium": 500,
  "font-weight.semibold": 650,
  "font-weight.bold": 750,
  "font-weight.black": 850,
  "text.xs": "0.75rem",
  "text.sm": "0.875rem",
  "text.md": "1rem",
  "text.lg": "1.125rem",
  "text.xl": "1.375rem",
  "text.2xl": "clamp(1.75rem, 3vw, 2.5rem)",
  "text.3xl": "clamp(2.25rem, 5vw, 4rem)",
  "text.display": "clamp(3rem, 7vw, 6.75rem)",
  "leading.tight": 0.98,
  "leading.heading": 1.08,
  "leading.body": 1.58,
  "control.sm": {
    "value": 36,
    "unit": "px"
  },
  "control.md": {
    "value": 44,
    "unit": "px"
  },
  "control.lg": {
    "value": 52,
    "unit": "px"
  },
  "layout.container": "90rem",
  "layout.content": "48rem",
  "radius.xs": {
    "value": 4,
    "unit": "px"
  },
  "radius.sm": {
    "value": 8,
    "unit": "px"
  },
  "radius.md": {
    "value": 12,
    "unit": "px"
  },
  "radius.lg": {
    "value": 16,
    "unit": "px"
  },
  "radius.xl": {
    "value": 24,
    "unit": "px"
  },
  "radius.control": {
    "value": 10,
    "unit": "px"
  },
  "radius.card": {
    "value": 16,
    "unit": "px"
  },
  "radius.pill": {
    "value": 999,
    "unit": "px"
  },
  "shadow.sm": "0 1px 2px rgb(29 29 31 / 6%)",
  "shadow.md": "0 12px 34px rgb(29 29 31 / 10%)",
  "shadow.lg": "0 24px 70px rgb(29 29 31 / 16%)",
  "duration.fast": {
    "value": 120,
    "unit": "ms"
  },
  "duration.base": {
    "value": 180,
    "unit": "ms"
  },
  "duration.slow": {
    "value": 280,
    "unit": "ms"
  },
  "ease.standard": "cubic-bezier(0.2, 0, 0, 1)",
  "z.dropdown": 30,
  "z.sticky": 40,
  "z.modal": 50,
  "z.toast": 60,
  "accent.strategy": "#8f6cad",
  "accent.ux": "#aa2d8a",
  "accent.technology": "#244d7e",
  "accent.implementation": "#4d7fb8",
  "accent.talent": "#e75a36",
  "accent.events": "#ec7b19",
  "color.brand": "#ff5a00",
  "color.action-primary": "#b93800",
  "color.action-primary-hover": "#932f08",
  "color.action-primary-active": "#77290d",
  "color.action-primary-text": "#ffffff",
  "color.brand-soft": "#fff4ed",
  "color.action-text": "#a33200",
  "color.canvas": "#ffffff",
  "color.surface": "#f5f2f0",
  "color.surface-raised": "#ffffff",
  "color.surface-hover": "#faf9f8",
  "color.text": "#1d1d1f",
  "color.text-muted": "#575350",
  "color.text-subtle": "#797471",
  "color.text-inverse": "#ffffff",
  "color.border": "#e7e3e0",
  "color.border-strong": "#a8a29e",
  "color.focus": "#b93800",
  "color.overlay": "rgb(13 13 14 / 64%)",
  "color.agent-thinking": "#24548a",
  "color.agent-running": "#b93800",
  "color.agent-awaiting": "#7a4d00",
  "color.agent-success": "#147d57",
  "color.agent-failed": "#b42318",
  "color.agent-paused": "#575350",
  "color.risk-low": "#147d57",
  "color.risk-medium": "#7a4d00",
  "color.risk-high": "#b42318",
  "button.background": "#1d1d1f",
  "button.background-primary": "#b93800",
  "button.background-primary-hover": "#932f08",
  "button.background-primary-active": "#77290d",
  "button.text-primary": "#ffffff",
  "button.background-brand": "#b93800",
  "button.height": {
    "value": 44,
    "unit": "px"
  },
  "button.radius": {
    "value": 999,
    "unit": "px"
  },
  "card.background": "#ffffff",
  "card.background-warm": "#f5f2f0",
  "card.radius": {
    "value": 16,
    "unit": "px"
  },
  "input.background": "#ffffff",
  "input.border": "#e7e3e0",
  "input.height": {
    "value": 44,
    "unit": "px"
  },
  "input.radius": {
    "value": 10,
    "unit": "px"
  },
  "dialog.background": "#ffffff",
  "dialog.radius": {
    "value": 24,
    "unit": "px"
  },
  "dialog.shadow": "0 24px 70px rgb(29 29 31 / 16%)",
  "badge.radius": {
    "value": 999,
    "unit": "px"
  },
  "badge.height": {
    "value": 28,
    "unit": "px"
  },
  "agent-status.thinking": "#24548a",
  "agent-status.running": "#b93800",
  "agent-status.awaiting": "#7a4d00",
  "agent-status.success": "#147d57",
  "agent-status.failed": "#b42318",
  "tool-call.background": "#ffffff",
  "tool-call.border": "#e7e3e0",
  "tool-call.radius": {
    "value": 16,
    "unit": "px"
  },
  "approval.background": "#ffffff",
  "approval.border": "#7a4d00",
  "approval.radius": {
    "value": 16,
    "unit": "px"
  },
  "artifact.background": "#ffffff",
  "artifact.border": "#e7e3e0",
  "artifact.radius": {
    "value": 16,
    "unit": "px"
  }
} as const;

export type DesignTokenPath = keyof typeof flatTokens;
