import type { ShowcaseGroupId } from './registry';

export type CatalogStatus = 'stable' | 'planned' | 'alias';

export type CatalogEntry = {
  id: string;
  name: string;
  href: string;
  groupId: ShowcaseGroupId;
  status: CatalogStatus;
  /** Manifest package id when different from catalog id */
  manifestId?: string;
  description: string;
  aliasOf?: string;
  /** Improve-only surface beyond the shared shadcn-like list */
  improveOnly?: boolean;
};

/**
 * Unified specimen index: one row per navigable primitive (and aliases).
 * Anchors target `#${id}` panels in the showcase.
 */
export const catalogEntries: CatalogEntry[] = [
  // Shared / shadcn-inspired list
  {
    id: 'accordion',
    name: 'Accordion',
    href: '#accordion',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'overlays',
    description: 'Seções expansíveis para conteúdo longo.',
  },
  {
    id: 'alert',
    name: 'Alert',
    href: '#alert',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'feedback',
    description: 'Mensagem de status inline.',
  },
  {
    id: 'alert-dialog',
    name: 'Alert Dialog',
    href: '#alert-dialog',
    groupId: 'molecules-core',
    status: 'stable',
    description: 'Confirmação destrutiva ou irreversível.',
  },
  {
    id: 'aspect-ratio',
    name: 'Aspect Ratio',
    href: '#aspect-ratio',
    groupId: 'foundations',
    status: 'stable',
    description: 'Proporção estável para mídia.',
  },
  {
    id: 'attachment',
    name: 'Attachment',
    href: '#attachment',
    groupId: 'molecules-saas',
    status: 'stable',
    description: 'Arquivo anexado com metadados.',
  },
  {
    id: 'avatar',
    name: 'Avatar',
    href: '#avatar',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'data-display',
    description: 'Representação visual de pessoa.',
  },
  {
    id: 'badge',
    name: 'Badge',
    href: '#badge',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'feedback',
    description: 'Rótulo compacto de status.',
  },
  {
    id: 'breadcrumb',
    name: 'Breadcrumb',
    href: '#breadcrumb',
    groupId: 'molecules-core',
    status: 'alias',
    aliasOf: 'breadcrumbs',
    manifestId: 'data-display',
    description: 'Alias de Breadcrumbs.',
  },
  {
    id: 'breadcrumbs',
    name: 'Breadcrumbs',
    href: '#breadcrumbs',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'data-display',
    description: 'Trilha de navegação hierárquica.',
  },
  {
    id: 'bubble',
    name: 'Bubble',
    href: '#bubble',
    groupId: 'agentic',
    status: 'stable',
    description: 'Bolha de chat humana ou agente.',
  },
  {
    id: 'button',
    name: 'Button',
    href: '#button',
    groupId: 'atoms-core',
    status: 'stable',
    description: 'Ação principal ou secundária.',
  },
  {
    id: 'button-group',
    name: 'Button Group',
    href: '#button-group',
    groupId: 'atoms-saas',
    status: 'stable',
    description: 'Grupo de botões relacionados.',
  },
  {
    id: 'calendar',
    name: 'Calendar',
    href: '#calendar',
    groupId: 'molecules-saas',
    status: 'stable',
    description: 'Grade de datas para seleção avulsa.',
  },
  {
    id: 'card',
    name: 'Card',
    href: '#card',
    groupId: 'molecules-core',
    status: 'stable',
    description: 'Contêiner de conteúdo agrupado.',
  },
  {
    id: 'carousel',
    name: 'Carousel',
    href: '#carousel',
    groupId: 'molecules-core',
    status: 'stable',
    description: 'Slides com navegação por teclado.',
  },
  {
    id: 'chart',
    name: 'Chart',
    href: '#chart',
    groupId: 'atoms-saas',
    status: 'stable',
    description: 'Série simples bar/line sobre Sparkline.',
  },
  {
    id: 'checkbox',
    name: 'Checkbox',
    href: '#checkbox',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'form',
    description: 'Escolha booleana.',
  },
  {
    id: 'collapsible',
    name: 'Collapsible',
    href: '#collapsible',
    groupId: 'molecules-core',
    status: 'stable',
    description: 'Conteúdo revelável sob demanda.',
  },
  {
    id: 'combobox',
    name: 'Combobox',
    href: '#combobox',
    groupId: 'molecules-saas',
    status: 'stable',
    description: 'Busca e seleção em lista.',
  },
  {
    id: 'command',
    name: 'Command',
    href: '#command',
    groupId: 'molecules-saas',
    status: 'alias',
    aliasOf: 'command-palette',
    description: 'Alias de CommandPalette.',
  },
  {
    id: 'command-palette',
    name: 'Command Palette',
    href: '#command-palette',
    groupId: 'molecules-saas',
    status: 'stable',
    description: 'Paleta de comandos rápida.',
  },
  {
    id: 'context-menu',
    name: 'Context Menu',
    href: '#context-menu',
    groupId: 'molecules-core',
    status: 'stable',
    description: 'Menu contextual no alvo.',
  },
  {
    id: 'data-table',
    name: 'Data Table',
    href: '#data-table',
    groupId: 'molecules-core',
    status: 'alias',
    aliasOf: 'data-table-primitive',
    manifestId: 'data-display',
    description: 'Tabela de dados (DataTable).',
  },
  {
    id: 'data-table-primitive',
    name: 'DataTable',
    href: '#data-table-primitive',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'data-display',
    description: 'Tabela tabular com caption.',
  },
  {
    id: 'date-picker',
    name: 'Date Picker',
    href: '#date-picker',
    groupId: 'molecules-saas',
    status: 'stable',
    description: 'Seleção de data.',
  },
  {
    id: 'dialog',
    name: 'Dialog',
    href: '#dialog',
    groupId: 'organisms-brand',
    status: 'stable',
    description: 'Modal de interrupção curta.',
  },
  {
    id: 'direction',
    name: 'Direction',
    href: '#direction',
    groupId: 'foundations',
    status: 'stable',
    description: 'Provider e hook de direção (LTR/RTL).',
  },
  {
    id: 'drawer',
    name: 'Drawer',
    href: '#drawer',
    groupId: 'molecules-saas',
    status: 'stable',
    description: 'Painel lateral ou inferior.',
  },
  {
    id: 'dropdown-menu',
    name: 'Dropdown Menu',
    href: '#dropdown-menu',
    groupId: 'molecules-core',
    status: 'stable',
    description: 'Menu de ações a partir de um gatilho.',
  },
  {
    id: 'empty',
    name: 'Empty',
    href: '#empty',
    groupId: 'molecules-saas',
    status: 'alias',
    aliasOf: 'empty-state',
    description: 'Alias de EmptyState.',
  },
  {
    id: 'empty-state',
    name: 'Empty State',
    href: '#empty-state',
    groupId: 'molecules-saas',
    status: 'stable',
    description: 'Estado vazio com orientação.',
  },
  {
    id: 'field',
    name: 'Field',
    href: '#field',
    groupId: 'molecules-core',
    status: 'alias',
    aliasOf: 'form-field',
    manifestId: 'form',
    description: 'Alias de FormField.',
  },
  {
    id: 'form-field',
    name: 'Form Field',
    href: '#form-field',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'form',
    description: 'Campo com label, hint e erro.',
  },
  {
    id: 'hover-card',
    name: 'Hover Card',
    href: '#hover-card',
    groupId: 'molecules-core',
    status: 'stable',
    description: 'Prévia contextual ao focar/apontar.',
  },
  {
    id: 'input',
    name: 'Input',
    href: '#input',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'form',
    description: 'Entrada de texto de uma linha.',
  },
  {
    id: 'input-group',
    name: 'Input Group',
    href: '#input-group',
    groupId: 'molecules-core',
    status: 'stable',
    description: 'Composer com afixos ao redor do input.',
  },
  {
    id: 'input-otp',
    name: 'Input OTP',
    href: '#input-otp',
    groupId: 'molecules-core',
    status: 'stable',
    description: 'Slots de código de verificação.',
  },
  {
    id: 'item',
    name: 'Item',
    href: '#item',
    groupId: 'atoms-saas',
    status: 'stable',
    description: 'Linha reutilizável de lista ou menu.',
  },
  {
    id: 'kbd',
    name: 'Kbd',
    href: '#kbd',
    groupId: 'atoms-saas',
    status: 'stable',
    description: 'Tecla de atalho tipográfica.',
  },
  {
    id: 'label',
    name: 'Label',
    href: '#label',
    groupId: 'molecules-core',
    status: 'stable',
    description: 'Rótulo acessível de formulário.',
  },
  {
    id: 'marker',
    name: 'Marker',
    href: '#marker',
    groupId: 'atoms-saas',
    status: 'stable',
    description: 'Ponto de status ou timeline.',
  },
  {
    id: 'menubar',
    name: 'Menubar',
    href: '#menubar',
    groupId: 'organisms-brand',
    status: 'stable',
    description: 'Barra de menus desktop.',
  },
  {
    id: 'message',
    name: 'Message',
    href: '#message',
    groupId: 'agentic',
    status: 'stable',
    description: 'Mensagem genérica de conversa.',
  },
  {
    id: 'message-scroller',
    name: 'Message Scroller',
    href: '#message-scroller',
    groupId: 'agentic',
    status: 'stable',
    description: 'Viewport com stick-to-bottom.',
  },
  {
    id: 'native-select',
    name: 'Native Select',
    href: '#native-select',
    groupId: 'molecules-core',
    status: 'stable',
    description: 'Select nativo estilizado.',
  },
  {
    id: 'navigation-menu',
    name: 'Navigation Menu',
    href: '#navigation-menu',
    groupId: 'organisms-brand',
    status: 'stable',
    description: 'Menu de navegação desacoplado do header.',
  },
  {
    id: 'pagination',
    name: 'Pagination',
    href: '#pagination',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'data-display',
    description: 'Navegação entre páginas.',
  },
  {
    id: 'popover',
    name: 'Popover',
    href: '#popover',
    groupId: 'molecules-saas',
    status: 'stable',
    description: 'Painel flutuante ancorado.',
  },
  {
    id: 'progress',
    name: 'Progress',
    href: '#progress',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'feedback',
    description: 'Barra de progresso determinada.',
  },
  {
    id: 'questionnaire',
    name: 'Questionnaire',
    href: '#questionnaire',
    groupId: 'molecules-saas',
    status: 'stable',
    description: 'Fluxo guiado de perguntas.',
  },
  {
    id: 'questionnaire-new',
    name: 'QuestionnaireNew',
    href: '#questionnaire',
    groupId: 'molecules-saas',
    status: 'alias',
    aliasOf: 'questionnaire',
    description: 'Alias de documentação para Questionnaire.',
  },
  {
    id: 'radio-group',
    name: 'Radio Group',
    href: '#radio-group',
    groupId: 'molecules-core',
    status: 'alias',
    aliasOf: 'radio-set',
    manifestId: 'form',
    description: 'Alias de RadioSet.',
  },
  {
    id: 'radio-set',
    name: 'Radio Set',
    href: '#radio-set',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'form',
    description: 'Grupo de opções exclusivas.',
  },
  {
    id: 'resizable',
    name: 'Resizable',
    href: '#resizable',
    groupId: 'foundations',
    status: 'stable',
    description: 'Painéis com divisor arrastável.',
  },
  {
    id: 'scroll-area',
    name: 'Scroll Area',
    href: '#scroll-area',
    groupId: 'foundations',
    status: 'stable',
    description: 'Região com rolagem contida.',
  },
  {
    id: 'select',
    name: 'Select',
    href: '#select',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'form',
    description: 'Seleção Radix estilizada.',
  },
  {
    id: 'separator',
    name: 'Separator',
    href: '#separator',
    groupId: 'molecules-core',
    status: 'alias',
    aliasOf: 'divider',
    manifestId: 'data-display',
    description: 'Alias de Divider.',
  },
  {
    id: 'divider',
    name: 'Divider',
    href: '#divider',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'data-display',
    description: 'Separador visual horizontal.',
  },
  {
    id: 'sheet',
    name: 'Sheet',
    href: '#sheet',
    groupId: 'molecules-saas',
    status: 'stable',
    description: 'Painel lateral modal.',
  },
  {
    id: 'sidebar',
    name: 'Sidebar',
    href: '#sidebar',
    groupId: 'organisms-saas',
    status: 'stable',
    description: 'Navegação lateral de produto.',
  },
  {
    id: 'skeleton',
    name: 'Skeleton',
    href: '#skeleton',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'feedback',
    description: 'Placeholder de carregamento.',
  },
  {
    id: 'slider',
    name: 'Slider',
    href: '#slider',
    groupId: 'atoms-saas',
    status: 'stable',
    description: 'Controle de valor contínuo.',
  },
  {
    id: 'spinner',
    name: 'Spinner',
    href: '#spinner',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'feedback',
    description: 'Indicador de carregamento indeterminado.',
  },
  {
    id: 'switch',
    name: 'Switch',
    href: '#switch',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'form',
    description: 'Alternância imediata on/off.',
  },
  {
    id: 'table',
    name: 'Table',
    href: '#table',
    groupId: 'molecules-core',
    status: 'stable',
    description: 'Primitivos de tabela (Table/Header/…).',
  },
  {
    id: 'tabs',
    name: 'Tabs',
    href: '#tabs',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'overlays',
    description: 'Abas de conteúdo.',
  },
  {
    id: 'textarea',
    name: 'Textarea',
    href: '#textarea',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'form',
    description: 'Entrada multilinha.',
  },
  {
    id: 'toast',
    name: 'Toast',
    href: '#toast',
    groupId: 'molecules-saas',
    status: 'stable',
    description: 'Notificação temporária.',
  },
  {
    id: 'toggle',
    name: 'Toggle',
    href: '#toggle',
    groupId: 'atoms-saas',
    status: 'stable',
    description: 'Botão de pressão ligado/desligado.',
  },
  {
    id: 'toggle-group',
    name: 'Toggle Group',
    href: '#toggle-group',
    groupId: 'atoms-saas',
    status: 'stable',
    description: 'Grupo de toggles mutuamente exclusivos.',
  },
  {
    id: 'tooltip',
    name: 'Tooltip',
    href: '#tooltip',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'overlays',
    description: 'Dica breve ao focar/apontar.',
  },
  {
    id: 'typography',
    name: 'Typography',
    href: '#typography',
    groupId: 'foundations',
    status: 'stable',
    description: 'Heading, Text e hierarquia tipográfica.',
  },

  // Improve-only surfaces
  {
    id: 'layout',
    name: 'Layout',
    href: '#layout',
    groupId: 'foundations',
    status: 'stable',
    improveOnly: true,
    description: 'Container, Stack, Cluster, Grid, Section.',
  },
  {
    id: 'logo',
    name: 'Logo',
    href: '#logo',
    groupId: 'atoms-core',
    status: 'stable',
    improveOnly: true,
    description: 'Marca Improve.',
  },
  {
    id: 'chip',
    name: 'Chip',
    href: '#chip',
    groupId: 'atoms-saas',
    status: 'stable',
    improveOnly: true,
    description: 'Filtro selecionável compacto.',
  },
  {
    id: 'tag',
    name: 'Tag',
    href: '#tag',
    groupId: 'atoms-saas',
    status: 'stable',
    improveOnly: true,
    description: 'Rótulo semântico removível.',
  },
  {
    id: 'search-input',
    name: 'Search Input',
    href: '#search-input',
    groupId: 'atoms-saas',
    status: 'stable',
    improveOnly: true,
    description: 'Campo de busca com limpar.',
  },
  {
    id: 'password-input',
    name: 'Password Input',
    href: '#password-input',
    groupId: 'atoms-saas',
    status: 'stable',
    improveOnly: true,
    description: 'Senha com revelar.',
  },
  {
    id: 'number-input',
    name: 'Number Input',
    href: '#number-input',
    groupId: 'atoms-saas',
    status: 'stable',
    improveOnly: true,
    description: 'Número com steppers.',
  },
  {
    id: 'sparkline',
    name: 'Sparkline',
    href: '#sparkline',
    groupId: 'atoms-saas',
    status: 'stable',
    improveOnly: true,
    description: 'Mini série temporal.',
  },
  {
    id: 'stat',
    name: 'Stat',
    href: '#stat',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'data-display',
    improveOnly: true,
    description: 'Métrica destacada.',
  },
  {
    id: 'quote',
    name: 'Quote',
    href: '#quote',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'data-display',
    improveOnly: true,
    description: 'Citação editorial.',
  },
  {
    id: 'description-list',
    name: 'Description List',
    href: '#description-list',
    groupId: 'molecules-core',
    status: 'stable',
    improveOnly: true,
    description: 'Lista termo/definição.',
  },
  {
    id: 'stepper',
    name: 'Stepper',
    href: '#stepper',
    groupId: 'molecules-saas',
    status: 'stable',
    improveOnly: true,
    description: 'Progresso por etapas.',
  },
  {
    id: 'multi-select',
    name: 'Multi Select',
    href: '#multi-select',
    groupId: 'molecules-saas',
    status: 'stable',
    improveOnly: true,
    description: 'Seleção múltipla com tags.',
  },
  {
    id: 'date-range-picker',
    name: 'Date Range Picker',
    href: '#date-range-picker',
    groupId: 'molecules-saas',
    status: 'stable',
    improveOnly: true,
    description: 'Intervalo de datas.',
  },
  {
    id: 'time-picker',
    name: 'Time Picker',
    href: '#time-picker',
    groupId: 'molecules-saas',
    status: 'stable',
    improveOnly: true,
    description: 'Seleção de horário.',
  },
  {
    id: 'file-upload',
    name: 'File Upload',
    href: '#file-upload',
    groupId: 'molecules-saas',
    status: 'stable',
    improveOnly: true,
    description: 'Envio de arquivos.',
  },
  {
    id: 'app-shell',
    name: 'App Shell',
    href: '#app-shell',
    groupId: 'organisms-saas',
    status: 'stable',
    improveOnly: true,
    description: 'Casca de aplicação.',
  },
  {
    id: 'page-header',
    name: 'Page Header',
    href: '#page-header',
    groupId: 'organisms-saas',
    status: 'stable',
    improveOnly: true,
    description: 'Cabeçalho de página de produto.',
  },
  {
    id: 'metric-card',
    name: 'Metric Card',
    href: '#metric-card',
    groupId: 'organisms-saas',
    status: 'stable',
    improveOnly: true,
    description: 'Card de KPI.',
  },
  {
    id: 'data-grid',
    name: 'Data Grid',
    href: '#data-grid',
    groupId: 'organisms-saas',
    status: 'stable',
    improveOnly: true,
    description: 'Grade de dados interativa.',
  },
  {
    id: 'filter-bar',
    name: 'Filter Bar',
    href: '#filter-bar',
    groupId: 'organisms-saas',
    status: 'stable',
    improveOnly: true,
    description: 'Barra de filtros.',
  },
  {
    id: 'pricing-card',
    name: 'Pricing Card',
    href: '#pricing-card',
    groupId: 'organisms-saas',
    status: 'stable',
    improveOnly: true,
    description: 'Plano comercial.',
  },
  {
    id: 'activity-feed',
    name: 'Activity Feed',
    href: '#activity-feed',
    groupId: 'organisms-saas',
    status: 'stable',
    improveOnly: true,
    description: 'Feed temporal de atividade.',
  },
  {
    id: 'hero',
    name: 'Hero',
    href: '#hero',
    groupId: 'organisms-brand',
    status: 'stable',
    manifestId: 'marketing',
    improveOnly: true,
    description: 'Hero institucional.',
  },
  {
    id: 'feature-card',
    name: 'Feature Card',
    href: '#feature-card',
    groupId: 'organisms-brand',
    status: 'stable',
    manifestId: 'marketing',
    improveOnly: true,
    description: 'Card de capacidade.',
  },
  {
    id: 'ecosystem-card',
    name: 'Ecosystem Card',
    href: '#ecosystem-card',
    groupId: 'organisms-brand',
    status: 'stable',
    manifestId: 'marketing',
    improveOnly: true,
    description: 'Card de ecossistema.',
  },
  {
    id: 'service-panel',
    name: 'Service Panel',
    href: '#service-panel',
    groupId: 'organisms-brand',
    status: 'stable',
    manifestId: 'marketing',
    improveOnly: true,
    description: 'Painel de serviço.',
  },
  {
    id: 'logo-cloud',
    name: 'Logo Cloud',
    href: '#logo-cloud',
    groupId: 'organisms-brand',
    status: 'stable',
    manifestId: 'marketing',
    improveOnly: true,
    description: 'Nuvem de logos.',
  },
  {
    id: 'site-header',
    name: 'Site Header',
    href: '#site-header',
    groupId: 'organisms-brand',
    status: 'stable',
    manifestId: 'navigation',
    improveOnly: true,
    description: 'Header institucional.',
  },
  {
    id: 'footer',
    name: 'Footer',
    href: '#footer',
    groupId: 'organisms-brand',
    status: 'stable',
    manifestId: 'navigation',
    improveOnly: true,
    description: 'Rodapé institucional.',
  },
  {
    id: 'action-menu',
    name: 'Action Menu',
    href: '#action-menu',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'overlays',
    improveOnly: true,
    description: 'Menu de ações (ícone).',
  },
  {
    id: 'select-menu',
    name: 'Select Menu',
    href: '#select-menu',
    groupId: 'molecules-core',
    status: 'stable',
    manifestId: 'overlays',
    improveOnly: true,
    description: 'Menu de seleção rotulado.',
  },
  {
    id: 'slides',
    name: 'Slides',
    href: '#slides',
    groupId: 'presentation',
    status: 'stable',
    improveOnly: true,
    description: 'Primitivos 16:9.',
  },
  {
    id: 'agent-status',
    name: 'Agent Status',
    href: '#agent-status',
    groupId: 'agentic',
    status: 'stable',
    improveOnly: true,
    description: 'Estado da execução agentic.',
  },
  {
    id: 'streaming-message',
    name: 'Streaming Message',
    href: '#streaming-message',
    groupId: 'agentic',
    status: 'stable',
    improveOnly: true,
    description: 'Mensagem em streaming.',
  },
  {
    id: 'tool-call-card',
    name: 'Tool Call Card',
    href: '#tool-call-card',
    groupId: 'agentic',
    status: 'stable',
    improveOnly: true,
    description: 'Chamada de ferramenta.',
  },
  {
    id: 'approval-card',
    name: 'Approval Card',
    href: '#approval-card',
    groupId: 'agentic',
    status: 'stable',
    improveOnly: true,
    description: 'Aprovação humana.',
  },
  {
    id: 'run-timeline',
    name: 'Run Timeline',
    href: '#run-timeline',
    groupId: 'agentic',
    status: 'stable',
    improveOnly: true,
    description: 'Linha do tempo da execução.',
  },
  {
    id: 'agent-error',
    name: 'Agent Error',
    href: '#agent-error',
    groupId: 'agentic',
    status: 'stable',
    improveOnly: true,
    description: 'Erro recuperável do agente.',
  },
  {
    id: 'plan-steps',
    name: 'Plan Steps',
    href: '#plan-steps',
    groupId: 'agentic',
    status: 'stable',
    improveOnly: true,
    description: 'Etapas do plano.',
  },
  {
    id: 'artifact-card',
    name: 'Artifact Card',
    href: '#artifact-card',
    groupId: 'agentic',
    status: 'stable',
    improveOnly: true,
    description: 'Artefato gerado.',
  },
  {
    id: 'citation-list',
    name: 'Citation List',
    href: '#citation-list',
    groupId: 'agentic',
    status: 'stable',
    improveOnly: true,
    description: 'Fontes citadas.',
  },
  {
    id: 'permission-scope',
    name: 'Permission Scope',
    href: '#permission-scope',
    groupId: 'agentic',
    status: 'stable',
    improveOnly: true,
    description: 'Escopos de permissão.',
  },
  {
    id: 'agent-handoff',
    name: 'Agent Handoff',
    href: '#agent-handoff',
    groupId: 'agentic',
    status: 'stable',
    improveOnly: true,
    description: 'Transferência de contexto.',
  },
  {
    id: 'generated-ui-boundary',
    name: 'Generated UI Boundary',
    href: '#generated-ui-boundary',
    groupId: 'agentic',
    status: 'stable',
    improveOnly: true,
    description: 'Limite de UI gerada.',
  },
  {
    id: 'mcp-app-frame',
    name: 'MCP App Frame',
    href: '#mcp-app-frame',
    groupId: 'agentic',
    status: 'stable',
    improveOnly: true,
    description: 'Frame de app MCP.',
  },
  {
    id: 'trace-viewer',
    name: 'Trace Viewer',
    href: '#trace-viewer',
    groupId: 'agentic',
    status: 'stable',
    improveOnly: true,
    description: 'Rastreamento de execução.',
  },
  {
    id: 'segmented-control',
    name: 'Segmented Control',
    href: '#segmented-control',
    groupId: 'atoms-saas',
    status: 'stable',
    improveOnly: true,
    description: 'Controle segmentado (base do Toggle Group).',
  },
];

export const catalogById = new Map(catalogEntries.map((entry) => [entry.id, entry]));

export function catalogEntriesForGroup(groupId: ShowcaseGroupId): CatalogEntry[] {
  return catalogEntries.filter((entry) => entry.groupId === groupId);
}

export function sortedCatalogEntries(entries: CatalogEntry[] = catalogEntries): CatalogEntry[] {
  return [...entries].sort((a, b) => a.name.localeCompare(b.name, 'pt-BR'));
}
